stages:
  - build
  - test

build:
  image: amazoncorretto:16-alpine
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew assemble

test:
  image: amazoncorretto:16-alpine
  stage: test

  script:
    - chmod +x gradlew
    - ./gradlew check
