stages:
  - build

build-gradle:
  stage: build
  except:
    - java-syntax
    - pre-DI
    - DI-manual
  image: amazoncorretto:16-alpine
  services:
    - mysql:latest
  variables:
      # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
      MYSQL_DATABASE: tjvdb
      MYSQL_ROOT_PASSWORD: root
  script:
      - chmod +x gradlew
      - ./gradlew build
      - rm -f build/libs/*-plain.jar
      - java -Dspring.main.web-application-type=none -jar build/libs/*.jar
