### Get all products
GET http://localhost:8080/products
Accept: application/json

### Get one product with id 0
GET http://localhost:8080/products/0
Accept: application/json

### Create a product
POST http://localhost:8080/products
Accept: application/json
Content-Type: application/json

{
  "productName": "Banana",
  "price": 9.99 ,
  "productId": 0
}

### Update a product with id 0
PUT http://localhost:8080/products/0
Accept: application/json
Content-Type: application/json

{
  "productName": "Banana",
  "price": 9.99 ,
  "productId": 0
}

### Delete a product with id 0
DELETE http://localhost:8080/products/0
Accept: application/json



