### Get all orders
GET http://localhost:8080/orders
Accept: application/json

### Get one order with id 1
GET http://localhost:8080/orders/1
Accept: application/json

### Create an order
POST http://localhost:8080/orders
Accept: application/json
Content-Type: application/json

{
  "clientEmail": "emailExample@gmail.com",
  "productIdsDTOs":
  [
    1
  ]
}


### we could not change order if client has been deleted
### Update an order with id 1
PUT http://localhost:8080/orders/1
Accept: application/json
Content-Type: application/json

{
  "orderId": 1,
  "clientEmail": "emailExample@gmail.com",
  "productIdsDTOs":
  [
    1
  ]
}

### Delete an order with id 1
DELETE http://localhost:8080/orders/1
Accept: application/json

###ADDITIONAL
### Get orders by client email
GET http://localhost:8080/orders/client/emailExample@gmail.com
Accept: application/json

### Get orders which contains product with id
GET http://localhost:8080/orders/product/1
Accept: application/json




