### Get all orders
GET http://localhost:8080/orders
Accept: application/json

### Get one order with id 0
GET http://localhost:8080/orders/0
Accept: application/json

### Create an order
POST http://localhost:8080/orders
Accept: application/json
Content-Type: application/json

{
  "clientEmail": "emailExample@gmail.com",
  "productDTOs": []
}

### Update an order with id 0
PUT http://localhost:8080/orders/1
Accept: application/json
Content-Type: application/json

{
  "orderId": 1,
  "clientEmail": "emailExample@gmail.com",
  "productDTOs": []
}

### Delete an order with id 0
DELETE http://localhost:8080/orders/0
Accept: application/json



